# Generated by Django 3.1.2 on 2020-10-15 14:31
# pylint: disable=invalid-name
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
