# Generated by Django 3.1.8 on 2021-04-25 13:11
# pylint: disable=invalid-name
from django.db import migrations

import projectx.users.fields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_auto_20201015_1431"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=projectx.users.fields.LowercaseEmailField(max_length=255, unique=True),
        ),
    ]
