# Generated by Django 3.2.7 on 2021-11-09 22:46
# pylint: disable=invalid-name
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="anonymous",
            field=models.BooleanField(
                default=False, help_text="Whether the user is anonymous.", verbose_name="anonymous status"
            ),
        ),
    ]
