version: '2.3'

x-environment:
  &environment
  SECRET_KEY: "DEV_SECRET_KEY"
  JWT_SECRET: "DEV_JWT_SECRET"
  DEBUG: "True"
  # PYTHONASYNCIODEBUG: "True" # Enable to debug python async issues
  PUBLIC_IP: ${PUBLIC_IP-127.0.0.1}
  DJANGO_SETTINGS_MODULE: "projectx.settings"

  
services:

  projectx:
    hostname: projectx
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      << : *environment
      DATABASE_URL: 'psql://postgres:mysecretpassword@postgres:5432/postgres'
      CHANNELS_REDIS_URL: redis://redis:6379/0
      CACHE_URL: redis://redis:6379/1
    depends_on: 
      - redis
      - postgres
    volumes:
      - ./backend/projectx/:/home/user/projectx/
      - ./backend/config/:/home/user/config/

  postgres:
    hostname: postgres
    image: postgres:15.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  redis:
    image: redis:7.0.9
    ports:
        - "6379:6379"